emqx/emqx-operator

api/v1alpha2/emqxbroker_types.go, api/v1alpha2/emqxenterprise_types.go, config/crd/bases/apps.emqx.io_emqxbrokers.yaml, config/crd/bases/apps.emqx.io_emqxenterprises.yaml, config/samples/emqx/emqx.yaml, pkg/service/generator_test.go
to ACL, loadedPlugins, loadedModules
=> chore: rename aclConf, loadedPluginConf, loadedModulesConf

config/samples/emqx/emqx.yaml, pkg/service/generator.go
=> Revert "fix: fix the volume permission error"

apis/apps/v1beta1/emqxbroker_webhook.go, apis/apps/v1beta1/emqxbroker_webhook_test.go, apis/apps/v1beta1/emqxenterprise_webhook.go
when create resource and update resource
Signed-off-by: zhanghongtong <rory-z@outlook.com>
=> feat(api): validate the format of the image tag

RELEASE.md, config/manager/kustomization.yaml, config/samples/operator/controller.yaml, docs/user-guides/get-started.md
Signed-off-by: zhanghongtong <rory-z@outlook.com>
=> chore(release): pre release 1.1.1

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, deploy/charts/emqx-operator/values.yaml
Signed-off-by: zhanghongtong <rory-z@outlook.com>
=> chore: add issue templates

.github/ISSUE_TEMPLATE/config.yml
Signed-off-by: zhanghongtong <rory-z@outlook.com>
=> chore: add config for ISSUE_TEMPLATE

config/rbac/role.yaml, config/samples/emqx/v1beta1/emqx-ee.yaml, controllers/apps/ensure.go, controllers/apps/handler.go, controllers/apps/reconcile.go, pkg/service/generator.go
use druRunClient to get the completed object for comparison
=> feat: add dryRunClient for ensure

.github/workflows/cts.yaml, .github/workflows/test.yaml, apis/apps/v1beta1/emqxbroker_webhook.go, apis/apps/v1beta1/emqxbroker_webhook_test.go, apis/apps/v1beta1/emqxenterprise_webhook.go, apis/apps/v1beta1/env_type.go, config/samples/emqx/v1beta1/emqx-ee.yaml, pkg/service/generator.go
when emqx 4.4.x, use dns cluster
dns cluster needless serviceAccount
=> feat: support dns cluster for emqx

config/samples/emqx/v1beta2/emqx-ee.yaml, pkg/service/generator.go
update probe for emqx container
=> feat: add preStop command for emqx container

pkg/service/generator.go
For better execution of "emqx_ctl cluster leave"
=> feat: add terminationGracePeriodSeconds for emqx container

.github/workflows/cts.yaml, .github/workflows/issue.yaml, .github/workflows/release.yml, .github/workflows/test.yaml, .github/workflows/upgrade.yaml
Cancel v1beta1 for upgrade test cases
=> ci: add concurrency for workflows

.github/workflows/upgrade.yaml, controllers/apps/handler.go
this will fix issue for when update serviceTemplate, pods restarted
=> fix: do not set “patch-annotation“ for emqx custrom resource

.github/workflows/test.yaml, Makefile
=> ci: support goveralls

.github/workflows/release.yml
=> ci: update operator ci

.github/actions/deploy-operator/action.yaml, .github/workflows/test.yaml, .github/workflows/upgrade.yaml
=> ci: update cert-manager

.github/actions/deploy-emqx/action.yaml, .github/workflows/cts.yaml, .github/workflows/test.yaml, config/samples/emqx/v1beta3/emqx-ee.yaml, config/samples/emqx/v1beta3/emqx.yaml
Use full names instead of short names
=> ci: update deployment emqx action

config/samples/emqx/v1beta3/emqx-ee.yaml, controllers/apps/v1beta3/emqx_handler.go, controllers/apps/v1beta3/emqx_test.go, controllers/apps/v1beta3/suite_test.go
If exist PVC, set PodManagementPolicy = "Parallel", or else, set
PodManagementPolicy = "OrderedReady"
This can avoid to some extent the problem of cluster brain cleavage
=> feat: set the value of PodManagementPolicy based if the PVC is exist or not

apis/apps/v1beta3/emqx_interface.go, apis/apps/v1beta3/emqxbroker_types.go, apis/apps/v1beta3/emqxbroker_webhook.go, apis/apps/v1beta3/emqxenterprise_types.go, apis/apps/v1beta3/emqxenterprise_webhook.go, apis/apps/v1beta3/emqxplugin_webhook.go, apis/apps/v1beta3/webhook_validation_test.go, config/crd/bases/apps.emqx.io_emqxbrokers.yaml, config/crd/bases/apps.emqx.io_emqxenterprises.yaml, config/samples/emqx/v1beta3/emqx-ee.yaml, controllers/apps/v1beta3/emqx_handler.go, controllers/apps/v1beta3/emqx_test.go, controllers/apps/v1beta3/emqxplugin_controller.go, deploy/charts/emqx-operator/templates/crd-emqx-brokers.yaml, deploy/charts/emqx-operator/templates/crd-emqx-enterprise.yaml, deploy/manifests/emqx-operator-controller.yaml
feat: add userNamn and password to emqx spec
=> feat: add username and password  to EmqxTemplate

apis/apps/v1beta3/emqxbroker_types.go, apis/apps/v1beta3/emqxenterprise_types.go, apis/apps/v1beta3/emqxplugin_types.go, config/crd/bases/apps.emqx.io_emqxbrokers.yaml, config/crd/bases/apps.emqx.io_emqxenterprises.yaml, config/crd/bases/apps.emqx.io_emqxplugins.yaml, deploy/charts/emqx-operator/Chart.yaml, deploy/charts/emqx-operator/templates/crd-emqx-brokers.yaml, deploy/charts/emqx-operator/templates/crd-emqx-enterprise.yaml, deploy/charts/emqx-operator/templates/crd-emqx-plugin.yaml
Signed-off-by: bin <brian.xb.bian@gmail.com>
=> chore: add comments

controllers/apps/v1beta3/emqx_handler.go, controllers/apps/v1beta3/emqx_handler_test.go
the resources involved are acl, pluginsConfig, loadedPlugins, license .
=> style: add update method for various resources in emqx statefulSet

.github/workflows/upgrade.yaml, apis/apps/v1beta3/webhook_defaulting_test.go, config/samples/emqx/v1beta3/emqx-ee.yaml, config/samples/emqx/v1beta3/emqx.yaml, controllers/apps/v1beta3/emqx_handler.go, controllers/apps/v1beta3/emqx_handler_test.go, controllers/apps/v1beta3/emqxplugin_controller.go, docs/en_US/deployment/aws-eks-deployment.md, docs/en_US/deployment/azure-deployment.md, docs/en_US/getting-started/getting-started.md, docs/zh_CN/deployment/aliyun-ack-deployment.md, docs/zh_CN/deployment/aws-eks-deployment.md, docs/zh_CN/deployment/azure-deployment.md, docs/zh_CN/deployment/cce-deployment.md, docs/zh_CN/deployment/tencent-tke-deployment.md, docs/zh_CN/getting-started/getting-started.md, e2e/v1beta3/e2e_test.go, e2e/v1beta3/suite_test.go
Fix loaded_plugins erofs error
Only support emqx 4.4.8 and later
=> chore: delete loaded_plugins configmap

.github/workflows/deploy-docs.yaml
=> ci: update deploy docs action

deploy/charts/emqx-operator/templates/controller-manager.yaml
Fix https://github.com/emqx/emqx-operator/issues/376
=> fix(helm): fix podAnnotations not working

deploy/charts/emqx-operator/templates/webhook-mutating-configuration.yaml, deploy/charts/emqx-operator/templates/webhook-validating-configuration.yaml
=> fix(helm): remove hardcoded ns and svc name

controllers/apps/v2alpha1/emqx_controller.go, controllers/apps/v2alpha1/status_machine.go
Fix https://github.com/emqx/emqx-operator/issues/435
=> fix(v2alpha1): fix a crash in the main application when sts is not found

controllers/apps/v1beta4/api.go, controllers/apps/v1beta4/emqx_controller.go, controllers/apps/v1beta4/statefulset.go, controllers/apps/v1beta4/statefulset_util.go
Signed-off-by: Rory Z <rory-z@outlook.com>
=> chore(v1beta4): update statefulset functions

Makefile, config/crd/bases/apps.emqx.io_emqxbrokers.yaml, config/crd/bases/apps.emqx.io_emqxenterprises.yaml, config/crd/bases/apps.emqx.io_emqxes.yaml, config/crd/bases/apps.emqx.io_emqxplugins.yaml, deploy/charts/emqx-operator/crds/apps.emqx.io_emqxbrokers.yaml, deploy/charts/emqx-operator/crds/apps.emqx.io_emqxenterprises.yaml, deploy/charts/emqx-operator/crds/apps.emqx.io_emqxes.yaml, deploy/charts/emqx-operator/crds/apps.emqx.io_emqxplugins.yaml, docs/en_US/reference/v1beta4-reference.md
and add crd-ref-docs in Makefile
=> chore: add "maxDescLen=0" in controller gen crd options

config/default/kustomization.yaml
fix https://github.com/emqx/emqx-operator/issues/486
=> chore: add default labels in kustomization

deploy/charts/emqx-operator/README.md, deploy/charts/emqx-operator/templates/controller-manager.yaml, deploy/charts/emqx-operator/values.yaml
Reverts emqx/emqx-operator#493
=> Revert "chore(helm): rename cert secret name in helm value"

deploy/charts/emqx-operator/README.md, deploy/charts/emqx-operator/templates/controller-manager.yaml, deploy/charts/emqx-operator/values.yaml
Reverts emqx/emqx-operator#413
=> Revert "chore: support custom webhook server secret name"

.github/workflows/cts.yaml, .github/workflows/test.yaml, codecov.yaml
Signed-off-by: Rory Z <rory-z@outlook.com>
=> chore(ci): use codecov

controllers/apps/v1beta4/add_emqx_statefulset.go
Signed-off-by: He11c 13735599246@163.com
=> chore: optimize some add_emqx_statefulset functions

docs/en_US/deployment/azure-deployment.md
=> fix: spelling of storageclass

docs/en_US/deployment/gcp-gke-deployment.md
Hi, I would like to improve your docs to ease the deployment on GCP 🚀 
I've just added the English docs, so feel free to edit anything :)
=> docs: add GKE info

config/samples/emqx/v2alpha1/emqx-slim.yaml
Here I think you could update to the latest available version as specified in the documentation:
https://github.com/emqx/emqx-operator/blob/main/docs/en_US/getting-started/getting-started.md#deploy-emqx-5
=> Update image to the latest version

apis/apps/v2alpha1/status.go, config/crd/bases/apps.emqx.io_emqxes.yaml, controllers/apps/v2alpha1/add_emqx_repl.go, controllers/apps/v2alpha1/add_emqx_repl_test.go, controllers/apps/v2alpha1/add_listener.go, controllers/apps/v2alpha1/update_emqx_status.go, controllers/apps/v2alpha1/update_pod_conditions.go, deploy/charts/emqx-operator/templates/crds.yaml, docs/en_US/reference/v2alpha1-reference.md, e2e/v2alpha1/e2e_test.go
- Add new field `Edition` to the `EMQXNode` struct
- Create `checkRebalanceStatus` function to check load rebalance status for the pod
=> feat: check load rebalancer status for EMQX pods.

controllers/apps/v1beta4/add_listener.go, controllers/apps/v2alpha1/add_listener.go, e2e/v1beta4/e2e_test.go, e2e/v2alpha1/e2e_test.go
- Refactor code to use standalone functions for better modularity and readability
- Add function to retrieve all Pods belonging to the EMQX deployment
- Update e2e tests to check Pods and Endpoints and EndpointSlices and add more context to tests for better clarity.
=> feat: Manager endpoints resources

apis/apps/v2alpha1/status.go, apis/apps/v2alpha1/status_test.go, config/crd/bases/apps.emqx.io_emqxes.yaml, controllers/apps/v2alpha1/status_machine.go, docs/en_US/reference/v2alpha1-reference.md
- And sort EMQX status's nodes by uptime
=> feat(v2alpha1): add uptime in CR status

apis/apps/v1beta4/rebalance_types.go, apis/apps/v1beta4/rebalance_types_test.go, controllers/apps/v1beta4/rebalance_controller.go, controllers/apps/v1beta4/rebalance_controller_test.go, docs/en_US/reference/v1beta4-reference.md, docs/zh_CN/reference/v1beta4-reference.md, e2e/v1beta4/emqx_test.go, e2e/v1beta4/rebalance_test.go
=> test(rebalance): add more test case

apis/apps/v1beta4/emqxbroker_webhook.go, apis/apps/v1beta4/emqxbroker_webhook_test.go, apis/apps/v1beta4/emqxenterprise_webhook.go, apis/apps/v1beta4/emqxenterprise_webhook_test.go, apis/apps/v1beta4/spec_types.go, apis/apps/v2alpha1/emqx_types.go, apis/apps/v2alpha1/emqx_webhook.go, apis/apps/v2alpha1/emqx_webhook_test.go, config/crd/bases/apps.emqx.io_emqxes.yaml, config/manager/manager.yaml, controllers/apps/v1beta4/generated.go, controllers/apps/v1beta4/generated_test.go, controllers/apps/v2alpha1/generated.go, controllers/apps/v2alpha1/generated_test.go, deploy/charts/emqx-operator/templates/crds.yaml, deploy/charts/emqx-operator/values.yaml, docs/en_US/reference/v2alpha1-reference.md, internal/handler/handler.go
add more default value for k8s obj, to avoid frequent updates
=> fix: fix oom

e2e/v2alpha1/e2e_test.go, e2e/v2alpha1/suite_test.go
This reverts commit d7b192a83c2065563aa83d6562c0227e92a886c7.
=> Revert "test(e2e): emqx 5.0.22 have bug, so use 5.0.21"

RELEASE.md
Docs: fix broken links in RELEASE.md and API version
=> chore: change supported API version

config/samples/emqx/v2beta1/emqx-full.yaml, controllers/apps/v2beta1/add_emqx_core.go
Fixes: https://github.com/emqx/emqx-operator/issues/905
=> fix: fix volume template always update

docs/README.md
Fix: https://github.com/emqx/emqx-operator/issues/901
=> docs: add official docs links

controllers/apps/v1beta3/emqx_handler.go
Fixed the bug where the service port disappears when a node in the EMQX cluster crashes.
=> fix: fix service port error

apis/apps/v2beta1/emqx_types.go, config/crd/bases/apps.emqx.io_emqxes.yaml, controllers/apps/v2beta1/add_svc.go, controllers/apps/v2beta1/add_svc_test.go, deploy/charts/emqx-operator/templates/crd.emqxes.apps.emqx.io.yaml, docs/en_US/reference/v2beta1-reference.md, docs/zh_CN/reference/v2beta1-reference.md
Fix https://github.com/emqx/emqx-operator/issues/943
=> feat: add option to disable creation of services

internal/handler/handler.go
when svc type is nodePort or loadBalancer, the svc will always update
=> fix: fix always update svc

controllers/apps/v2beta1/update_pod_conditions.go
More info: https://github.com/emqx/emqx-operator/issues/998#issuecomment-1883023562
=> chore: don't always change lastTransitionTime of pod conditon

controllers/apps/v2beta1/emqx_controller.go
Fix https://github.com/emqx/emqx-operator/issues/1027
=> fix: fix sometimes can not update sts

.github/workflows/cts.yaml, .github/workflows/deploy.yaml, controllers/apps/v2beta1/add_headless_svc.go, controllers/apps/v2beta1/add_svc.go, controllers/apps/v2beta1/emqx_controller.go, controllers/apps/v2beta1/status_machine.go
Fix https://github.com/emqx/emqx-operator/issues/1036
=> fix: fix emqx cluster can not ready

docs/en_US/tasks/configure-emqx-core-replicant.md, docs/zh_CN/tasks/configure-emqx-core-replicant.md
fix: https://github.com/emqx/emqx-operator/issues/1040
=> docs: fix check status command error
