.gitignore, api/v1beta1/emqx.go, api/v1beta1/emqxbroker_types.go, api/v1beta1/emqxenterprise_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/apps.emqx.io_emqxbrokers.yaml, config/crd/bases/apps.emqx.io_emqxenterprises.yaml, pkg/service/generator.go
I believe that sometimes it is necessary to mount extra volumes like secrets and/or configmaps as additional volumes to treat EMQX plugins, e.g. mounting public JWT tokens to the brokers. Hope this will help to improve the early beginning of the operator.
=> Add extra volumes mount possibility

controllers/apps/emqx_handler.go, deploy/charts/emqx-operator/Chart.yaml
There is a risk that preStop will fail. When persistence is enabled, preStop failure can lead to inconsistent emqx cluster data
=> chore: delete preStop command

apis/apps/v1beta3/servicetemplate.go, controllers/apps/v1beta3/emqx_handler.go, controllers/apps/v1beta3/emqx_handler_test.go, e2e/v1beta3/e2e_test.go, pkg/handler/handler.go, pkg/handler/handler_test.go
move some annotations from metadata to spec.template.metadata, beacuse
statefulset's metadata can not update.
fix some error for compatible with 1.2.2
=> chore: format annotations for statefulSet

controllers/apps/v1beta3/emqx_handler.go, controllers/apps/v1beta3/emqx_handler_test.go
This fixes the issue of emqx clusters not being able to be deployed twice
=> chore: add PublishNotReadyAddresses for headless service

controllers/apps/v1beta3/emqx_handler.go
when append port to headless svc, ignore nodePort
=> fix: fix headless svc NodePort invaild

config/samples/emqx/v1beta3/emqxbroker-full.yaml, config/samples/emqx/v1beta3/emqxenterprise-full.yaml
change `serviceTemplate.type.spec` to nodePort and add some port exmaples in `./emqx-operator/config/samples/emqx/v1beta3/emqxbroker-full.yaml` and`./emqx-operator/config/samples/emqx/v1beta3/emqxenterprise-full.yaml`
=> docs: set service type to nodePort

apis/apps/v2alpha1/emqx_webhook.go, apis/apps/v2alpha1/names.go, controllers/apps/v2alpha1/emqx_controller.go, controllers/apps/v2alpha1/generated.go, controllers/apps/v2alpha1/generated_test.go
do not generate emqx node cookie in default webhook, generated it in generated functions.
fix https://github.com/emqx/emqx-operator/issues/480
=> fix(v2alpha1): fix can not update EMQX resource

deploy/charts/emqx-operator/Chart.yaml, deploy/charts/emqx-operator/templates/controller-manager-metrics-service.yaml, deploy/charts/emqx-operator/templates/controller-manager-webhook-service.yaml
We need to add extra labels to the Service selector to point explicitly to the correct pod in the namespace. It is pretty useful when you have much other stuff to be in the same namespace to avoid conflicts.
=> Add extra selectors to the Services

deploy/charts/emqx-operator/Chart.yaml, deploy/charts/emqx-operator/templates/controller-manager-rbac.yaml
The imagePullSecrets are not applied to the main emqx/emqx-operator-controller image. This PR includes the change to add the imagePullSecrets to the service account to be able to pull images from private registries.
=> feat: add imagepullsecret to service account.

docs/en_US/getting-started/getting-started.md, docs/zh_CN/getting-started/getting-started.md
- Use `kubectl wait` instead of `kubectl get` for checking EMQX Operator readiness.
- Update documentation in both English and Chinese for consistency.
- Simplify and improve Operator readiness checking steps in the Getting Started guides.
=> docs: Update EMQX Operator readiness check in docs

controllers/apps/v2alpha1/add_bootstrap_resource.go, controllers/apps/v2alpha1/add_emqx_core.go, controllers/apps/v2alpha1/add_emqx_repl.go, controllers/apps/v2alpha1/add_listener.go, controllers/apps/v2alpha1/add_svc.go, controllers/apps/v2alpha1/emqx_controller.go, controllers/apps/v2alpha1/status_machine.go, controllers/apps/v2alpha1/status_machine_test.go, controllers/apps/v2alpha1/update_emqx_status.go, controllers/apps/v2alpha1/update_pod_conditions.go
- Rename `CheckNodeCount` to `UpdateNodeCount` to better represent its functionality.
- Remove unused parameters and imports in various files.
- Refactor code to avoid unnecessary API calls and improve error handling.
- Update `UpdateStatus()` and `NextStatus()` methods for improved functionality.
- Clean up code formatting and remove commented out code.
=> refactor: Refactor EMQX controller reconciliation and cleanup.

.github/workflows/deploy-docs.yaml, .github/workflows/push-helm.yaml, .github/workflows/release.yml
And change regex for helm version check, support pre-release version
=> ci: when create release, do not use GITHUB_TOKEN

docs/en_US/getting-started/getting-started.md
Image version needs to be a string or else admission webhook errors. `4.4` is too old as well.
The current version of manifest fails to deploy, e.g.
```bash
Error from server: error when creating "emqx.yaml": admission webhook "mutating.broker.emqx.io" denied the request: json: cannot unmarshal number into Go struct field EmqxImage.spec.template.spec.emqxContainer.image.version of type string
Error from server (image version 4.4 is too old, please upgrade to 4.4.14 or later): error when creating "emqx.yaml": admission webhook "validator.broker.emqx.io" denied the request: image version 4.4 is too old, please upgrade to 4.4.14 or later
```
=> Image version needs to be a string

apis/apps/v2alpha2/emqx_webhook.go, apis/apps/v2alpha2/emqx_webhook_test.go
Avoid conflicting with validate create webhook.
=> chore(v2alpha2): don't format hocon in default webhook

sidecar/reloader/main.go
ioutil has been deprecated in Go 1.16
replace it with the io and os packages
=> fix: remove deprecated ioutil package

apis/apps/v2beta1/const.go, controllers/apps/v2beta1/sync_emqx_config.go, deploy/charts/emqx-operator/Chart.yaml, e2e/v2beta1/e2e_test.go
cancel sync EMQX config from EMQX API
fix https://github.com/emqx/emqx-operator/issues/983
=> fix: fix can not start new pod error

apis/apps/v2beta1/const.go, controllers/apps/v2beta1/sync_emqx_config.go
fix sometimes will access EMQX api, event emqx config not change.
fix configmap no have owner reference
=> fix: fix sometimes will update emqx config

controllers/apps/v2beta1/sync_emqx_config.go
=> fix: fix update emqx config error

controllers/apps/v2beta1/update_emqx_status.go
When the EMQX resource is in `coreNodesProgressing/replicantNodesProgressing` state, if the user manually deletes `currentSts/currentRs`, it will cause a nil point error.
=> fix: fix nil point error

deploy/charts/emqx-operator/Chart.yaml
This allows renovate to generate the changelog in update PRs
=> build: Set sources list in helm chart

controllers/apps/v2beta1/emqx_controller.go
some times operator controller will pick deleted pod to request EMQX API
=> fix: selector pod to request EMQX API

.github/workflows/cts.yaml, .github/workflows/deploy.yaml, config/rbac/role.yaml, controllers/apps/v2beta1/add_pdb.go, controllers/apps/v2beta1/emqx_controller.go, deploy/charts/emqx-operator/Chart.yaml, deploy/charts/emqx-operator/templates/controller-manager-rbac.yaml, main.go
Fix https://github.com/emqx/emqx-operator/issues/1023
=> feat: add pdb

.github/actions/deploy-operator/action.yaml, .github/workflows/build-reloader-image.yaml, .github/workflows/cts.yaml, .github/workflows/release.yml, config/samples/emqx/v2beta1/emqx-full.yaml, controllers/apps/v2beta1/add_pdb.go
Fix https://github.com/emqx/emqx-operator/issues/1045
=> fix: support pdb in kube 1.20

apis/apps/v2beta1/status.go, config/crd/bases/apps.emqx.io_emqxes.yaml, deploy/charts/emqx-operator/Chart.yaml, deploy/charts/emqx-operator/templates/crd.emqxes.apps.emqx.io.yaml, docs/en_US/reference/v2beta1-reference.md, docs/zh_CN/reference/v2beta1-reference.md
Fix https://github.com/emqx/emqx-operator/issues/1052
=> chore: delete uptime in status

.github/workflows/cts.yaml, .github/workflows/release.yml
fix: https://github.com/emqx/emqx-operator/issues/1063
=> ci: push multi image to ghcr when release

RELEASE.md, controllers/apps/v2beta1/update_emqx_status.go
Reverts emqx/emqx-operator#1067
=> Revert "fix: fix nil pointer error"
